from . import test_correction_editing
from . import test_correction_reporting
from . import test_correction_payment
from . import test_correction_stock
from . import test_correction_lifecycle
from . import test_correction_debt
from . import test_correction_security
from . import test_correction_concurrency
from . import test_correction_views
from . import test_correction_pos_sync
